name: CommandOmaExample
description: Example plugin for CommandOma. Written and tested by Cory Torode.
version: 1.0
# api-version: 1.19.4-R0.1-SNAPSHOT
main: oma.command.example.CommandOmaExample
author: Cory Torode